version: 2.1

executors:
  python:
    parameters:
      image_tag:
        type: string
        default: "python:3.7"

    docker:
      - image: circleci/<< parameters.image_tag >>

commands:
  installation:
    parameters:
      test_requirements:
        type: boolean
        default: false

      latest_featuretools:
        type: boolean
        default: false

    steps:
      - checkout
      - run:
          name: "Install the requirements in a virtual environment."
          command: |
            virtualenv env -q
            source env/bin/activate
            pip config --site set global.progress_bar off
            pip install .

      - when:
          condition: << parameters.test_requirements >>
          steps:
            - run:
                name: "Install the test requirements."
                command: |
                  source env/bin/activate
                  pip install -r test-requirements.txt

      - when:
          condition: << parameters.latest_featuretools >>
          steps:
            - run:
                name: "Install the latest Featuretools from master branch."
                command: |
                  source env/bin/activate
                  pip install git+https://github.com/FeatureLabs/featuretools.git@master#egg=featuretools --upgrade

jobs:
  lint_tests:
    working_directory: ~/featuretools-tsfresh-primitives
    parameters:
      image_tag:
        type: string
        default: "python:3.7"

    executor:
      name: python
      image_tag: << parameters.image_tag >>

    steps:
      - installation
      - run:
          name: "Install Test Requirements"
          command: |
            source env/bin/activate
            pip install -r test-requirements.txt

      - run:
          name: "Run Lint Tests"
          command: |
            source env/bin/activate
            make lint-tests

  unit_tests:
    working_directory: ~/featuretools-tsfresh-primitives
    parameters:
      image_tag:
        type: string
        default: "python:3.7"

      latest_featuretools:
        type: boolean
        default: false

      codecov:
        type: boolean
        default: false

    executor:
      name: python
      image_tag: << parameters.image_tag >>

    steps:
      - installation:
          test_requirements: true
          latest_featuretools: << parameters.latest_featuretools >>

      - run:
          name: "Run Unit Tests"
          command: |
            source env/bin/activate
            pytest -n 2 --cov=featuretools_tsfresh_primitives --cache-clear --show-capture=stderr -vv

      - when:
          condition: << parameters.codecov >>
          steps:
            - run: |
                source env/bin/activate
                codecov


  entry_point_test:
    working_directory: ~/featuretools-tsfresh-primitives
    parameters:
      image_tag:
        type: string
        default: "python:3.7"

      latest_featuretools:
        type: boolean
        default: false

    executor:
      name: python
      image_tag: << parameters.image_tag >>

    steps:
      - installation:
          latest_featuretools: << parameters.latest_featuretools >>

      - run:
          name: "Verify installed packages have compatible dependencies."
          command: |
            source env/bin/activate
            pip check

      - run:
          name: "Test Entry Point"
          command: |
            source env/bin/activate
            python -c "from featuretools import tsfresh"

workflows:
  version: 2
  "Integration Tests":
    jobs:
      - lint_tests:
          name: "Lint Tests - Python 3.5"
          image_tag: "python:3.5"

      - lint_tests:
          name: "Lint Tests - Python 3.6"
          image_tag: "python:3.6"

      - lint_tests:
          name: "Lint Tests - Python 3.7"
          image_tag: "python:3.7"

      - unit_tests:
          name: "Unit Tests - Python 3.5 - Featuretools Release"
          image_tag: "python:3.5"

      - unit_tests:
          name: "Unit Tests - Python 3.6 - Featuretools Release"
          image_tag: "python:3.6"

      - unit_tests:
          name: "Unit Tests - Python 3.7 - Featuretools Release"
          image_tag: "python:3.7"

      - unit_tests:
          name: "Unit Tests - Python 3.5 - Featuretools Master"
          image_tag: "python:3.5"
          latest_featuretools: true

      - unit_tests:
          name: "Unit Tests - Python 3.6 - Featuretools Master"
          image_tag: "python:3.6"
          latest_featuretools: true

      - unit_tests:
          name: "Unit Tests - Python 3.7 - Featuretools Master"
          image_tag: "python:3.7"
          latest_featuretools: true
          codecov: true

      - entry_point_test:
          name: "Entry Point Test - Python 3.5 - Featuretools Release"
          image_tag: "python:3.5"

      - entry_point_test:
          name: "Entry Point Test - Python 3.6 - Featuretools Release"
          image_tag: "python:3.6"

      - entry_point_test:
          name: "Entry Point Test - Python 3.7 - Featuretools Release"
          image_tag: "python:3.7"

      - entry_point_test:
          name: "Entry Point Test - Python 3.5 - Featuretools Master"
          image_tag: "python:3.5"
          latest_featuretools: true

      - entry_point_test:
          name: "Entry Point Test - Python 3.6 - Featuretools Master"
          image_tag: "python:3.6"
          latest_featuretools: true

      - entry_point_test:
          name: "Entry Point Test - Python 3.7 - Featuretools Master"
          image_tag: "python:3.7"
          latest_featuretools: true
