version: 2.1

executors:
  python:
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    docker:
      - image: circleci/<< parameters.image_tag >>

commands:
  installation:
    steps:
      - checkout
      - run:
          name: "Install Package in Virtual Environment"
          command: |
            virtualenv env -q
            source env/bin/activate
            pip install . -q

jobs:
  unit_tests:
    working_directory: ~/featuretools-tsfresh-primitives
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: "Install Test Requirements"
          command: |
            source env/bin/activate
            pip install -r test-requirements.txt -q
      - run:
          name: "Run Unit Tests"
          command: |
            source env/bin/activate
            pytest --cache-clear --show-capture=stderr -vv

  entry_point_test:
    working_directory: ~/featuretools-tsfresh-primitives
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: "Test Entry Point"
          command: |
            source env/bin/activate
            python -c "from featuretools import tsfresh"

workflows:
  version: 2
  integration_test:
    jobs:
      - unit_tests:
          name: "Unit Tests - Python 3.5"
          image_tag: "python:3.5"
      - unit_tests:
          name: "Unit Tests - Python 3.6"
          image_tag: "python:3.6"
      - unit_tests:
          name: "Unit Tests - Python 3.7"
          image_tag: "python:3.7"
      - entry_point_test:
          name: "Entry Point Test - Python 3.5"
          image_tag: "python:3.5"
      - entry_point_test:
          name: "Entry Point Test - Python 3.6"
          image_tag: "python:3.6"
      - entry_point_test:
          name: "Entry Point Test - Python 3.7"
          image_tag: "python:3.7"